[package]
name = "rs-matter-macros-impl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.33"
rs-matter-data-model={path = "../rs-matter-data-model", features = ["idl"]}
proc-macro2 = "1.0.70"
convert_case = "0.6.0"

[dev-dependencies]
assert-tokenstreams-eq = "0.1.0"
syn = {version="2.0.41", features = ["extra-traits"]}
