name: Test-Linux-OpenSSL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        crypto-backend: ['crypto_openssl', 'crypto_rustcrypto', 'crypto_mbedtls']

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd matter; cargo build --verbose --no-default-features --features ${{matrix.crypto-backend}}
    - name: Run tests
      run: cd matter; cargo test --verbose --no-default-features --features ${{matrix.crypto-backend}} -- --test-threads=1
