name: Test-Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        crypto-backend: ['rustcrypto', 'mbedtls', 'openssl']

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cd matter; cargo build --no-default-features --features ${{matrix.crypto-backend}}
    - name: Run tests
      run: cd matter; cargo test --no-default-features --features os,${{matrix.crypto-backend}} -- --test-threads=1
